### ISSUE TITLE
Reactive Design and CSS

### ISSUE THREAD

**Issue by darenkeck** [Margorah/CharSheetNg2#11]
Look at how we are going to support mobile and desktop layouts. Integrate any potential libraries (bootstrap.css?)

**Comment by darenkeck** [comment]
At some point we do want to migrate this with something like Nativescript or Ionic.  We probably need to investigate what is supported for styling.

**Comment by Margorah** [comment]
I really like the the potential performance gains from using native api calls. How much structure and styling rewrite would be required? Ionic has a really good docs page and, I hazard to guess, easier to transfer over since it's a webview. 

Bootstrap could be used at first to get a presentable webapp and we could attempt to move to one of the others if we aren't tired of the whole thing by then. How much of a pain would it be to have boostrap styling as a branch of develop and push develop changes to the boostrap branch?

**Comment by darenkeck** [comment]
It looks like we may be able to rely on ionics components for styling so perhaps this is no longer an issue.
